name: build

on:
  push:
    paths:
      - "src/**"
      - "*.json"

jobs:
  # build-node:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.x, 20.x, 22.x]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: npm install
  #     - run: npm run build --if-present
  #     - run: npm test
  #       env:
  #         CI: true

  # publish-npm:
  #   needs: build-node
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     # Setup .npmrc file to publish to npm
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: "20.x"
  #         registry-url: "https://registry.npmjs.org"
  #     - run: npm install
  #     - run: npm test
  #     - uses: codecov/codecov-action@v1
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-deno:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-targets: [{ "target": "x86_64-unknown-linux-gnu", "dir": "linux-x86_64"}, { "target": "aarch64-unknown-linux-gnu", "dir": "linux-aarch64"}, { "target": "x86_64-pc-windows-msvc", "dir": "windows-x86_64"}, { "target": "x86_64-apple-darwin", "dir": "macos-x86_64"}, { "target": "aaarch64-apple-darwin", "dir": "macos-aaarch64" } ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build executable ${{ matrix.compile-targets }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: "2.0.2"
      - run: deno install
      - run: deno test --allow-env --allow-read --allow-sys --coverage --trace-leaks src/
      - run: deno compile --allow-env --allow-read --allow-write --allow-sys --allow-net --target ${{ matrix.compile-targets.target }} -o bin/${{ matrix.compile-targets.dir }}/srrup src/index.ts
      - uses: actions/upload-artifact@v4
        with:
          name: srrup-${{ matrix.compile-targets.dir }}
          path: bin/${{ matrix.compile-targets.dir }}/srrup*
          retention-days: 7

  release-github:
    needs: build-deno
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: bin
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -alhR bin
      # - name: Release
      #   uses: softprops/action-gh-release@v2
