name: build

on:
  push:
    paths:
      - "src/**"
      - "*.json"

jobs:

  build-deno:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-targets: [{ "target": "x86_64-unknown-linux-gnu", "dir": "linux-x86_64"}, { "target": "aarch64-unknown-linux-gnu", "dir": "linux-aarch64"}, { "target": "x86_64-pc-windows-msvc", "dir": "windows-x86_64"}, { "target": "x86_64-apple-darwin", "dir": "macos-x86_64"}, { "target": "aarch64-apple-darwin", "dir": "macos-aarch64" } ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build executable ${{ matrix.compile-targets }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install
      - run: deno test --allow-env --allow-read --allow-sys --coverage --trace-leaks src/
      - run: deno compile --allow-env --allow-read --allow-write --allow-sys --allow-net --target ${{ matrix.compile-targets.target }} -o bin/${{ matrix.compile-targets.dir }}/srrup src/index.ts
      - uses: actions/upload-artifact@v4
        with:
          name: srrup-${{ matrix.compile-targets.dir }}
          path: bin/${{ matrix.compile-targets.dir }}/srrup*
          retention-days: 7

  release-github:
    needs: build-deno
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: bin
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -alhR bin
      # - name: Release
      #   uses: softprops/action-gh-release@v2
